#!/usr/bin/env bash



# Minify the CSS
gsed ':a;N;$!ba;s/\n//g;s/: /:/g;s/ {  /{/g;s/;  /;/g;s/;}/}/g' \
         "${SITE_ROOT}/templates/styles.css" > "${SITE_ROOT}/templates/styles.min.css"


render_from_into() {
    local src="$1"
    local dst="$2"
    local dry="$3"

    echo "rendering from $src to $dst ; dry run? = $dry"

    for file in $(git ls-files -m $src | grep '\.md$'); do

        base=$(basename $file)
        title=${base%%.md}
        
        echo "... rendering $file -> ${dst}/${title}.html"
        
        [ "$dry" == "dry" ] && continue
        pandoc -t html5 \
            --template="${SITE_ROOT}/templates/template.html" \
            --include-in-header="${SITE_ROOT}/templates/styles.min.css" \
            --metadata title="Brian Tracy - $title" \
            --metadata date="$(date)" \
            "$file" |
            gsed ':a;N;$!ba;s|>\s*<|><|g' \
            > "${dst}/${title}.html"
    done
}

render_from_into "${SITE_ROOT}/markdown" "${SITE_ROOT}/.."
