#!/usr/bin/env bash

[ -z ${REPO_ROOT} ] && \
    { echo "REPO_ROOT must be defined to execute this script" ; exit 1 ; }

CSS_FILE=$(mktemp)

# Compile and Minify the CSS
sass "${REPO_ROOT}/_site/styles.scss" --style=compressed > "${CSS_FILE}"


# OSX differs from linux, of course
modification_date() {
    stat -f "%Sm" "$1"
}

for mdfile in $(find ${REPO_ROOT} -name '*.md'); do
    base_name="${mdfile%.*}"
    html_file="${base_name}.html"
    mod_date=$(modification_date $mdfile)
    echo "$mdfile -> $html_file ($mod_date)"
    
    pandoc --to html5 --from markdown-auto_identifiers \
        --template="${REPO_ROOT}/_site/template.html" \
        --include-in-header="${CSS_FILE}" \
        --metadata title="Brian Tracy - $(basename $base_name)" \
        --metadata date="${mod_date}" \
        --ascii \
        "${mdfile}" \
        | html-minifier --no-html5 --collapse-whitespace --remove-comments \
        > "${html_file}"
done

